apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-db
  namespace: classflow
spec:
  selector:
    matchLabels:
      app: notification-db
  serviceName: notification-db
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: classflow-db-secrets
                  key: notification-db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: classflow-db-secrets
                  key: notification-db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: classflow-db-secrets
                  key: notification-db-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-db
  namespace: classflow
spec:
  selector:
    app: notification-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
