server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://notification-db:5432/notification_db
    driver-class-name: org.postgresql.Driver
    username: notification_user
    password: notification_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: false
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: false
    out-of-order: false
  h2:
    console:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: tu_email@gmail.com
    password: tu_contraseña
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    notificaciones_service: DEBUG