apiVersion: v1
kind: ConfigMap
metadata:
  name: classflow-config
  namespace: classflow
data:
  SPRING_PROFILES_ACTIVE: "docker"
  ENTRA_ISSUER_URI: "https://login.microsoftonline.com/981c9c3d-2cb3-493c-8b5e-bcf013a445e3/v2.0"
  ENTRA_API_AUDIENCE: "api://d3ec09df-b3b2-420c-b0dc-8b5534f58462"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  AUTH_SERVICE_URL: "http://ms-auth:8081"
