server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: bff-service
          uri: http://bff:8086
          predicates:
            - Path=/api/bff/**
          filters:
            - StripPrefix=0

        - id: auth-service
          uri: http://auth:8081  # 🔥 Usa el nombre del servicio
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        
        - id: academic-service-courses
          uri: http://academic:8082  # 🔥 Usa el nombre del servicio
          predicates:
            - Path=/api/courses/**,/api/subjects/**,/api/evaluations/**,/api/grades/**
          filters:
            - StripPrefix=0
        
        - id: assistance-service
          uri: http://assistance:8083
          predicates:
            - Path=/api/attendance/**,/api/annotations/**
          filters:
            - StripPrefix=0
        
        - id: message-service
          uri: http://message:8084
          predicates:
            - Path=/api/messages/**,/api/announcements/**
          filters:
            - StripPrefix=0
        
        - id: notification-service
          uri: http://notification:8085
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0