spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    driver-class-name: org.postgresql.Driver
    username: auth_user
    password: auth_pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: false
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: false
    out-of-order: false
    validate-on-migrate: false
    encoding: UTF-8
  h2:
    console:
      enabled: false

server:
  port: 8081